//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompetitionInvitesWCF.CompetitionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/CompetitionInvitesWCFService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocialNetworkInterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicalInterestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialNetworkInterest {
            get {
                return this.SocialNetworkInterestField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialNetworkInterestField, value) != true)) {
                    this.SocialNetworkInterestField = value;
                    this.RaisePropertyChanged("SocialNetworkInterest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicalInterest {
            get {
                return this.TechnicalInterestField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicalInterestField, value) != true)) {
                    this.TechnicalInterestField = value;
                    this.RaisePropertyChanged("TechnicalInterest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attend", Namespace="http://schemas.datacontract.org/2004/07/CompetitionInvitesWCFService")]
    [System.SerializableAttribute()]
    public partial class Attend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcceptRegretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StudentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcceptRegret {
            get {
                return this.AcceptRegretField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptRegretField, value) != true)) {
                    this.AcceptRegretField = value;
                    this.RaisePropertyChanged("AcceptRegret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Student {
            get {
                return this.StudentField;
            }
            set {
                if ((this.StudentField.Equals(value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompetitionService.ICompetitionService")]
    public interface ICompetitionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findAllStudent", ReplyAction="http://tempuri.org/ICompetitionService/findAllStudentResponse")]
        CompetitionInvitesWCF.CompetitionService.Student[] findAllStudent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findAllStudent", ReplyAction="http://tempuri.org/ICompetitionService/findAllStudentResponse")]
        System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Student[]> findAllStudentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findStudentId", ReplyAction="http://tempuri.org/ICompetitionService/findStudentIdResponse")]
        CompetitionInvitesWCF.CompetitionService.Student[] findStudentId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findStudentId", ReplyAction="http://tempuri.org/ICompetitionService/findStudentIdResponse")]
        System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Student[]> findStudentIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findAllAttend", ReplyAction="http://tempuri.org/ICompetitionService/findAllAttendResponse")]
        CompetitionInvitesWCF.CompetitionService.Attend[] findAllAttend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findAllAttend", ReplyAction="http://tempuri.org/ICompetitionService/findAllAttendResponse")]
        System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Attend[]> findAllAttendAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findAttendId", ReplyAction="http://tempuri.org/ICompetitionService/findAttendIdResponse")]
        CompetitionInvitesWCF.CompetitionService.Attend[] findAttendId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/findAttendId", ReplyAction="http://tempuri.org/ICompetitionService/findAttendIdResponse")]
        System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Attend[]> findAttendIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/InsertIntoDB", ReplyAction="http://tempuri.org/ICompetitionService/InsertIntoDBResponse")]
        void InsertIntoDB(CompetitionInvitesWCF.CompetitionService.Student student, CompetitionInvitesWCF.CompetitionService.Attend attend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetitionService/InsertIntoDB", ReplyAction="http://tempuri.org/ICompetitionService/InsertIntoDBResponse")]
        System.Threading.Tasks.Task InsertIntoDBAsync(CompetitionInvitesWCF.CompetitionService.Student student, CompetitionInvitesWCF.CompetitionService.Attend attend);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompetitionServiceChannel : CompetitionInvitesWCF.CompetitionService.ICompetitionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompetitionServiceClient : System.ServiceModel.ClientBase<CompetitionInvitesWCF.CompetitionService.ICompetitionService>, CompetitionInvitesWCF.CompetitionService.ICompetitionService {
        
        public CompetitionServiceClient() {
        }
        
        public CompetitionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompetitionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompetitionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompetitionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CompetitionInvitesWCF.CompetitionService.Student[] findAllStudent() {
            return base.Channel.findAllStudent();
        }
        
        public System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Student[]> findAllStudentAsync() {
            return base.Channel.findAllStudentAsync();
        }
        
        public CompetitionInvitesWCF.CompetitionService.Student[] findStudentId(int id) {
            return base.Channel.findStudentId(id);
        }
        
        public System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Student[]> findStudentIdAsync(int id) {
            return base.Channel.findStudentIdAsync(id);
        }
        
        public CompetitionInvitesWCF.CompetitionService.Attend[] findAllAttend() {
            return base.Channel.findAllAttend();
        }
        
        public System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Attend[]> findAllAttendAsync() {
            return base.Channel.findAllAttendAsync();
        }
        
        public CompetitionInvitesWCF.CompetitionService.Attend[] findAttendId(int id) {
            return base.Channel.findAttendId(id);
        }
        
        public System.Threading.Tasks.Task<CompetitionInvitesWCF.CompetitionService.Attend[]> findAttendIdAsync(int id) {
            return base.Channel.findAttendIdAsync(id);
        }
        
        public void InsertIntoDB(CompetitionInvitesWCF.CompetitionService.Student student, CompetitionInvitesWCF.CompetitionService.Attend attend) {
            base.Channel.InsertIntoDB(student, attend);
        }
        
        public System.Threading.Tasks.Task InsertIntoDBAsync(CompetitionInvitesWCF.CompetitionService.Student student, CompetitionInvitesWCF.CompetitionService.Attend attend) {
            return base.Channel.InsertIntoDBAsync(student, attend);
        }
    }
}
